<a href="https://colab.research.google.com/github/vanessabriggith/python/blob/main/EjerciciosPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# 1. Import numpy as np and see the version

import numpy as np
np.__version__


'1.22.4'

In [35]:
# 2. Create a 1D array of numbers from 0 to 9
import numpy as np
a = np.array([0, 1, 2,3,4,5,6,7,8,9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
# 3. Create a 3×3 numpy array of all True’s
import numpy as np
n=np.full((3, 3), True)
print(n)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [37]:
# 4. Extract all odd numbers from arr
import numpy as np
a = np.array([0, 1, 2,3,4,5,6,7,8,9])
print(a[a % 2 == 1])


[1 3 5 7 9]


In [38]:
from numpy.core.fromnumeric import clip
# 5. Replace all odd numbers in arr with -1

import numpy as np
a = np.array([0, 1, 2,3,4,5,6,7,8,9])
a1=(a[a % 2 == 1])
result=np.clip(a1,0,-1)
print(result)




[-1 -1 -1 -1 -1]


In [39]:
#  6. Convert a 1D array to a 2D array with 2 rows
a = np.array((10,20,30))
b = np.array((20,30,40))
#print(a,b)
print(np.column_stack((a,b)))

[[10 20]
 [20 30]
 [30 40]]


In [40]:
#  7. Stack arrays a and b vertically
import numpy as np
a = np.array([[5], [6], [7]])
b = np.array([[8], [9], [10]])
print(np.vstack((a,b)))

[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [41]:
#  8. Stack the arrays a and b horizontally.
import numpy as np
a = np.array((8,9,10))
b = np.array((11,12,13))
print(np.hstack((a,b)))

[ 8  9 10 11 12 13]


In [42]:
#  9. Get all items between 5 and 10 from a.
import numpy as np
someList=list()
someList=['borrador','cuaderno','goma','vasos','esfero','lapiz','mouse','peinilla','agua','mascarilla','calculadora']
print (someList[5:10])

['lapiz', 'mouse', 'peinilla', 'agua', 'mascarilla']


In [43]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

import numpy as np
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

max_a = None
for a1 in a:
    if (max_a is None or a1 > max_a):
        max_a = a1


max_b = None
for b1 in b:
    if (max_b is None or b1 > max_b):
        max_b = b1

print('Valor maximo de A:',max_a,'Valor maximo de B:' ,max_b)

Valor maximo de A: 9 Valor maximo de B: 9


In [45]:
#  11. Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

import numpy as np
arr = np.arange(9).reshape(3,3)
print("Original")
print(arr)

def Swap(arr, start_index, last_index):
    arr[:, [start_index, last_index]] = arr[:, [last_index, start_index]]
Swap(arr, 0, 1)
print("Intercamnio:")
print(arr)

Original
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Intercamnio:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [53]:
#  12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]
import numpy as np
array = np.random.uniform(5, 10, size=(5, 3))
print(array)


[[6.52911998 6.41148573 9.86151444]
 [9.39463087 7.24857447 9.04712717]
 [5.80828134 9.87530982 5.22051773]
 [9.86988575 6.10289142 9.8539461 ]
 [6.92832123 9.01943019 6.12886097]]
